version: '3.9'

services:

  pgadmin:
    container_name: pg_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - '4033:4033'
    volumes:
      - /VAR/LIB/PGADMIN

