docker-compose.yml
version: '3'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        links:
            - db
    db:
        image: "postgres:9.6"
        ports:
            - "5432:5432"